services:
  - type: web
    name: veiltrader-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BASE_NETWORK
        value: sepolia
      - key: GROQ_API_KEY
        sync: false
      - key: BANKR_API_KEY
        sync: false
      - key: WALLET_ADDRESS
        value: "0x03a33E8A69f1A5b61178f70BC5c8E674aB571334"
      - key: PRIVATE_KEY
        sync: false
      - key: UNISWAP_API_KEY
        sync: false
      - key: DEMO_MODE
        value: "false"
      - key: EMERGENCY_STOP
        value: "false"
